name: Deploy to AWS Server

on:
  push:
    branches:
      - vy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.AWS_PEM_KEY }}

    - name: Copy files to AWS server
      run: |
        rsync -avz -e "ssh -o StrictHostKeyChecking=no -i $HOME/.ssh/aws-cdn-hk.pem" ./ ubuntu@${{ secrets.AWS_SERVER_IP }}:/usr/share/nginx/officialWebsite/tg

    - name: Install dependencies
      run: |
        ssh -o StrictHostKeyChecking=no -i $HOME/.ssh/aws-cdn-hk.pem ubuntu@${{ secrets.AWS_SERVER_IP }} 'sudo su -c "cd /usr/share/nginx/officialWebsite/tg && npm install"'

    - name: Restart application
      run: |
        ssh -o StrictHostKeyChecking=no -i $HOME/.ssh/aws-cdn-hk.pem ubuntu@${{ secrets.AWS_SERVER_IP }} 'sudo su -c "sudo systemctl restart nginx'
